/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gtrefs' at '05.07.16 16:25' with Gradle 2.13
 *
 * @author gtrefs, @date 05.07.16 16:25
 */
public class Lambdafy {
    public boolean someLibraryMethod() {
        return true;
    }
}
